//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESERVATION_SYSTEM.Infrastructure.Constants {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageConstants() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RESERVATION_SYSTEM.Infrastructure.Constants.MessageConstants", typeof(MessageConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT [Id]
        ///      ,[Name]
        ///      ,[Email]
        ///      ,[Phone]
        ///      ,[DateRegistration]
        ///  FROM [Reservation].[dbo].[Customer]
        ///  {0}.
        /// </summary>
        internal static string GetCustomers {
            get {
                return ResourceManager.GetString("GetCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select * from (
        /// SELECT 
        ///  h.[ReservationID]
        ///  ,h.[DateChange]
        ///  ,h.[DescriptionChange]
        ///  ,s.[Name] as ServiceName
        ///  ,c.[name] as CustomerName
        /// FROM 
        ///  [Reservation].[dbo].[HistoryReservation] as h
        /// inner join Reservation.dbo.Reservation as r on r.Id = h.ReservationID
        /// inner join Reservation.dbo.Customer as c on c.id = r.[CustomerID]
        /// inner join Reservation.dbo.[Service] as s on s.id = r.ServiceID
        ///) as s
        ///{0}.
        /// </summary>
        internal static string GetHistoryReservation {
            get {
                return ResourceManager.GetString("GetHistoryReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select * from (
        /// SELECT 
        ///  r.[Id]
        ///    ,r.[CustomerID]
        ///    ,c.[name] as CustomerName
        ///    ,r.[ServiceID]
        ///    ,s.[Name] as ServiceName
        ///    ,r.[DateReservation]
        ///    ,r.[StartDate]
        ///    ,r.[EndDate]
        ///    ,r.[State]
        ///    ,r.[NumberPeople]
        ///    ,r.[Total]
        ///   FROM [Reservation].[dbo].[Reservation] as r
        ///   inner join Reservation.dbo.Customer as c on c.id = r.[CustomerID]
        ///   inner join Reservation.dbo.[Service] as s on s.id = r.ServiceID
        ///  ) as s
        ///  {0}.
        /// </summary>
        internal static string GetReservation {
            get {
                return ResourceManager.GetString("GetReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT  [Id]
        ///      ,[Name]
        ///      ,[Description]
        ///      ,[Price]
        ///      ,[Capacity]
        ///      ,[Available]
        ///  FROM [Reservation].[dbo].[Service]
        ///{0}
        ///.
        /// </summary>
        internal static string GetServices {
            get {
                return ResourceManager.GetString("GetServices", resourceCulture);
            }
        }
    }
}
